### ISSUE TITLE
fix hat commit

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#93]
After the birthday date was over, eligible emotes came out as "undefined emote". Cannot reproduce in local version, so it seems related to the date expiring while chat is still loaded.

Also, onstreamchat broke since the update.

**Comment by xDashh** [comment]
https://github.com/MemeLabs/chat-gui/commit/6af054b7fb0beec48daaff0a2cb03f0842d6fdf0#diff-4f24595caa90170de9accc7ca874f505R117 missing `return` if no case is hit @slugalisk @KenanY for next code review :^)

Will push patch momentarily.

**Comment by KenanY** [comment]
That PR landed without my approval (and not all of the comments I did leave were addressed) 😢

**Comment by xDashh** [comment]
Oh nvm then, it was a time-critical update after all, so stuff happens.

Reopening though because onstreamchat is still broken by this. Any ideas @KenanY ?
link is `https://chat.strims.gg/chatstreamed`

**Comment by KenanY** [comment]
@xDashh @Oreganon [this code](https://github.com/MemeLabs/chat-gui/blame/master/assets/chat/js/formatters.js#L150-L151) throws in onstreamchat because there is no emote menu there:

```
​​document.getElementsByClassName(...)[0] is undefined
```

**Comment by xDashh** [comment]
Closed by https://github.com/MemeLabs/chat-gui/commit/38a08e515e46b6e5e1c5dd92920b48b5ea539daf
